apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: mon-metric-grafana
type: Opaque
stringData:
  MINIO_ACCESS_KEY: L7eyFIgYlKRUivfaaXIU
  MINIO_SECRET_KEY: tmqx8db1ABc3VhCAhj1RBlQBAbDcZGqsSFaksJEV
  MINIO_REGION: us-east-1