apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-credentials
  namespace: mon-metric-grafana
type: Opaque
stringData:
  host: 192.168.1.252
  port: "5432"
  database: grafana_stage
  username: grafanauser
  password: grafana
